config/routes.rb
Rails.application.routes.draw do

  resources :brassicas

end

app/models/brassica.rb
class Brassica < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/brassicas_controller.rb
class BrassicasController < ApplicationController

  #this is the GET
  def index
    @brassicas = Brassica.all
  end

  # this is a GET
  def show
    @brassica = Brassica.find(params[:id])
  end

  # GET
  def new
    @brassica = Brassica.new
  end

   # POST 
  def create
    Brassica.create(brassica_params)
    redirect_to(brassicas_path)
  end

   # GET
  def edit
    @brassica = Brassica.find(params[:id])
  end

  # PUT
  def update
    @brassica = Brassica.find(params[:id])
    @brassica.update(brassica_params)
    redirect_to(brassicas_path)
  end

   # DELETE
  def destroy
    brassica = Brassica.find(params[:id])
    brassica.destroy
    redirect_to(brassicas_path)
  end


private
  def brassica_params
    params.require(:brassica).permit(:name, :colour, :average_height, :edible)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/Brassicas/edit.html.erb
<%= form_for @brassica do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :colour %>
  <%= f.text_field :colour %>

  <%= f.label :average_height %>
  <%= f.text_field :average_height %>

  <%= f.label :edible %>
  <%= f.text_field :edible %>

  <%= f.submit 'UPDATE BRASSICA' %>
  
<% end %>

app/views/Brassicas/index.html.erb
<h3>WELCOME TO THE EXCITING WORLD OF THE BRASSICA FAMILY</h3>

<ul class="list-group">
  <% @brassicas.each do |brassica| %>
    <div class="list-group-item">
      <ul class="brassica">
        <li class="brassica_name"><%= link_to(brassica.name, brassica_path(brassica.id))%></li>  
        <li><%= link_to('DELETE', brassica_path(brassica.id), method: :delete) %></li>
        <li><%= link_to('EDIT', edit_brassica_path(brassica.id)) %></li>
    </div>
  <% end %>
</ul>

app/views/Brassicas/new.html.erb
<%= form_for @brassica do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :colour %>
  <%= f.text_field :colour %>

  <%= f.label :average_height %>
  <%= f.text_field :average_height %>

  <%= f.label :edible %>
  <%= f.text_field :edible %>

  <%= f.submit 'CREATE BRASSICA' %>
  
<% end %>

app/views/Brassicas/show.html.erb
<div class="brassica-info">
 <h3><%= @brassica.name %></h3>

 <h4>Colour: <%= @brassica.colour%></h4>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrassicaFamily</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
 <li><%= link_to('Brassicacae', brassicas_path)%></li>
  <li><%= link_to('New Brassica', new_brassica_path)%></li>
</nav>

<%= yield %>

</body>
</html>